// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Astro.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Astro.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Astro__AgileCtsMapGen__calculateMapKey_name = "calculateMapKey";

const ::std::string __Astro__AgileCtsMapGen__shutdown_name = "shutdown";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::Astro::upCast(::IceProxy::Astro::AgileCtsMapGen* p) { return p; }

void
::IceProxy::Astro::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Astro::AgileCtsMapGen>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Astro::AgileCtsMapGen;
        v->__copyFrom(proxy);
    }
}

::Astro::Matrix
IceProxy::Astro::AgileCtsMapGen::calculateMapKey(const ::Astro::AGILECtsMapGenParams& param, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Astro__AgileCtsMapGen__calculateMapKey_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Astro__AgileCtsMapGen__calculateMapKey_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Astro::AgileCtsMapGen* __del = dynamic_cast< ::IceDelegate::Astro::AgileCtsMapGen*>(__delBase.get());
            return __del->calculateMapKey(param, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Astro::AgileCtsMapGen::begin_calculateMapKey(const ::Astro::AGILECtsMapGenParams& param, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Astro__AgileCtsMapGen__calculateMapKey_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Astro__AgileCtsMapGen__calculateMapKey_name, __del, __cookie);
    try
    {
        __result->__prepare(__Astro__AgileCtsMapGen__calculateMapKey_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(param);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Astro::Matrix
IceProxy::Astro::AgileCtsMapGen::end_calculateMapKey(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Astro__AgileCtsMapGen__calculateMapKey_name);
    ::Astro::Matrix __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::Astro::AgileCtsMapGen::shutdown(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Astro__AgileCtsMapGen__shutdown_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Astro::AgileCtsMapGen* __del = dynamic_cast< ::IceDelegate::Astro::AgileCtsMapGen*>(__delBase.get());
            __del->shutdown(__ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Astro::AgileCtsMapGen::begin_shutdown(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Astro__AgileCtsMapGen__shutdown_name, __del, __cookie);
    try
    {
        __result->__prepare(__Astro__AgileCtsMapGen__shutdown_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Astro::AgileCtsMapGen::end_shutdown(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Astro__AgileCtsMapGen__shutdown_name);
}

const ::std::string&
IceProxy::Astro::AgileCtsMapGen::ice_staticId()
{
    return ::Astro::AgileCtsMapGen::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Astro::AgileCtsMapGen::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Astro::AgileCtsMapGen);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Astro::AgileCtsMapGen::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Astro::AgileCtsMapGen);
}

::IceProxy::Ice::Object*
IceProxy::Astro::AgileCtsMapGen::__newInstance() const
{
    return new AgileCtsMapGen;
}

::Astro::Matrix
IceDelegateM::Astro::AgileCtsMapGen::calculateMapKey(const ::Astro::AGILECtsMapGenParams& param, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Astro__AgileCtsMapGen__calculateMapKey_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(param);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Astro::Matrix __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::Astro::AgileCtsMapGen::shutdown(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Astro__AgileCtsMapGen__shutdown_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::Astro::Matrix
IceDelegateD::Astro::AgileCtsMapGen::calculateMapKey(const ::Astro::AGILECtsMapGenParams& param, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Astro::Matrix& __result, const ::Astro::AGILECtsMapGenParams& __p_param, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_param(__p_param)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Astro::AgileCtsMapGen* servant = dynamic_cast< ::Astro::AgileCtsMapGen*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->calculateMapKey(_m_param, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Astro::Matrix& _result;
        const ::Astro::AGILECtsMapGenParams& _m_param;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Astro__AgileCtsMapGen__calculateMapKey_name, ::Ice::Normal, __context);
    ::Astro::Matrix __result;
    try
    {
        _DirectI __direct(__result, param, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::Astro::AgileCtsMapGen::shutdown(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Astro::AgileCtsMapGen* servant = dynamic_cast< ::Astro::AgileCtsMapGen*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->shutdown(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Astro__AgileCtsMapGen__shutdown_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(__current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* Astro::upCast(::Astro::AgileCtsMapGen* p) { return p; }

namespace
{
const ::std::string __Astro__AgileCtsMapGen_ids[2] =
{
    "::Astro::AgileCtsMapGen",
    "::Ice::Object"
};

}

bool
Astro::AgileCtsMapGen::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Astro__AgileCtsMapGen_ids, __Astro__AgileCtsMapGen_ids + 2, _s);
}

::std::vector< ::std::string>
Astro::AgileCtsMapGen::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Astro__AgileCtsMapGen_ids[0], &__Astro__AgileCtsMapGen_ids[2]);
}

const ::std::string&
Astro::AgileCtsMapGen::ice_id(const ::Ice::Current&) const
{
    return __Astro__AgileCtsMapGen_ids[0];
}

const ::std::string&
Astro::AgileCtsMapGen::ice_staticId()
{
    return __Astro__AgileCtsMapGen_ids[0];
}

::Ice::DispatchStatus
Astro::AgileCtsMapGen::___calculateMapKey(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Astro::AGILECtsMapGenParams param;
    __is->read(param);
    __inS.endReadParams();
    ::Astro::Matrix __ret = calculateMapKey(param, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Astro::AgileCtsMapGen::___shutdown(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    shutdown(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Astro__AgileCtsMapGen_all[] =
{
    "calculateMapKey",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "shutdown"
};

}

::Ice::DispatchStatus
Astro::AgileCtsMapGen::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Astro__AgileCtsMapGen_all, __Astro__AgileCtsMapGen_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Astro__AgileCtsMapGen_all)
    {
        case 0:
        {
            return ___calculateMapKey(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___shutdown(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Astro::AgileCtsMapGen::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Astro::AgileCtsMapGen::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Astro::__patch(AgileCtsMapGenPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Astro::AgileCtsMapGenPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Astro::AgileCtsMapGen::ice_staticId(), v);
    }
}
