// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `DBAstro.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="DBAgileEvt", key="double", value="Astro::agileEvt"
// name="DBAgileEvtStruct", key="double", value="Astro::agileEvtValue"
// name="DBAgileLog", key="Astro::agileLogKey", value="Astro::agileLog"

#ifndef __code_DBAstro_h__
#define __code_DBAstro_h__

#include <Freeze/Map.h>
#include </home/userdev3/Projects/gtCtsMapGen/code/Astro.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

class DBAgileEvtKeyCodec
{
public:

    static void write(::Ice::Double, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Double&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class DBAgileEvtValueCodec
{
public:

    static void write(const ::Astro::agileEvt&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Astro::agileEvt&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Double, ::Astro::agileEvt, DBAgileEvtKeyCodec, DBAgileEvtValueCodec, Freeze::IceEncodingCompare > DBAgileEvt;

class DBAgileEvtStructKeyCodec
{
public:

    static void write(::Ice::Double, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Double&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class DBAgileEvtStructValueCodec
{
public:

    static void write(const ::Astro::agileEvtValue&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Astro::agileEvtValue&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Double, ::Astro::agileEvtValue, DBAgileEvtStructKeyCodec, DBAgileEvtStructValueCodec, Freeze::IceEncodingCompare > DBAgileEvtStruct;

class DBAgileLogKeyCodec
{
public:

    static void write(const ::Astro::agileLogKey&, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Astro::agileLogKey&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class DBAgileLogValueCodec
{
public:

    static void write(const ::Astro::agileLog&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Astro::agileLog&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Astro::agileLogKey, ::Astro::agileLog, DBAgileLogKeyCodec, DBAgileLogValueCodec, Freeze::IceEncodingCompare > DBAgileLog;

#endif
